baseurl = "/"
title = "AmIDev blog"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "amidevpl@gmail.com"
disqusShortname = "XXX"
publishDir = "docs"

[Privacy]

[Privacy.disqus]
    disable = true

[Author]
    name = "My Name"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "AmIDev blog"
    description = "Ghostwriter example description"
    github = "https://github.com/XXX"
    email = "XXX@example.com"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Estimated reading time:"
    fathomUrl = ""
    fathomSiteId = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
